export const APP_INITIALIZE              = 'APP_INITIALIZE'
export const APP_UPDATE_STATUS           = 'APP_UPDATE_STATUS'
export const APP_STATUS_CONNECTED        = 'APP_STATUS_CONNECTED'
export const APP_STATUS_CONNECTING       = 'APP_STATUS_CONNECTING'
export const APP_STATUS_ERROR            = 'APP_STATUS_ERROR'
export const APP_STATUS_INITIALIZED      = 'APP_STATUS_INITIALIZED'
export const APP_SET_DIALOG              = 'APP_SET_DIALOG'

export const MESSAGE_TOGGLE_PROPERTY     = 'MESSAGE_TOGGLE_PROPERTY'
export const MESSAGE_REMOVE              = 'MESSAGE_REMOVE'
export const MESSAGE_MARK_ALL_READ       = 'MESSAGE_MARK_ALL_READ'

export const CHANNEL_UPDATE              = 'CHANNEL_UPDATE'
export const CHANNEL_VOLUME_UPDATE       = 'CHANNEL_VOLUME_UPDATE'
