export const APP_INITIALIZE               = 'APP_INITIALIZE'
export const APP_SET_DIALOG               = 'APP_SET_DIALOG'
export const APP_SET_DIFF                 = 'APP_SET_DIFF'
export const APP_STATUS_CONNECTED         = 'APP_STATUS_CONNECTED'
export const APP_STATUS_CONNECTING        = 'APP_STATUS_CONNECTING'
export const APP_STATUS_ERROR             = 'APP_STATUS_ERROR'
export const APP_STATUS_INITIALIZED       = 'APP_STATUS_INITIALIZED'
export const APP_UPDATE_STATUS            = 'APP_UPDATE_STATUS'

export const MESSAGE_ADD                  = 'MESSAGE_ADD'
export const MESSAGE_BULK_ADD             = 'MESSAGE_BULK_ADD'
export const MESSAGE_MARK_ALL_READ        = 'MESSAGE_MARK_ALL_READ'
export const MESSAGE_REMOVE               = 'MESSAGE_REMOVE'
export const MESSAGE_TOGGLE_PROPERTY      = 'MESSAGE_TOGGLE_PROPERTY'
export const MESSAGE_STAR                 = 'MESSAGE_STAR'
export const MESSAGE_UNSTAR               = 'MESSAGE_UNSTAR'
export const MESSAGE_WINDOW_GROW          = 'MESSAGE_WINDOW_GROW'
export const MESSAGE_WINDOW_REQUEST_OLDER = 'MESSAGE_WINDOW_REQUEST_OLDER'

export const CHANNEL_CONTACT_UPDATE       = 'CHANNEL_CONTACT_UPDATE'
export const CHANNEL_SET_MUTED            = 'CHANNEL_SET_MUTED'
export const CHANNEL_UPDATE               = 'CHANNEL_UPDATE'
export const CHANNEL_VOLUME_UPDATE        = 'CHANNEL_VOLUME_UPDATE'

export const TOASTR_ADD_MESSAGE           = 'TOASTR_ADD_MESSAGE'
export const TOASTR_REFRESH               = 'TOASTR_REFRESH'
export const TOASTR_REMOVE_MESSAGE        = 'TOASTR_REMOVE_MESSAGE'
